### ISSUE TITLE
%HOME% instead of C:\Documents and Settings\user

### ISSUE THREAD

**Issue by mslinn** [eed3si9n/color-themes#1]
It is best to refer to a windows user home directory via %HOME%. This works with all versions of Windows. Type it into the URL bar of file manager or in at a dos prompt. The docs refer to:

```
 C:\Documents and Settings\user\.IntelliJIDEA10CE\config\colors
```

... but it would be better to say:

```
%HOME%\.IntelliJIDEA10CE\config\colors
```

**Comment by eed3si9n** [comment]
I actually tested this and `%HOME%` works in neither XP nor Vista.

**Comment by mslinn** [comment]
Sorry, should have been  %HOMEPATH%. A list of predefined environment variables is here: http://en.wikipedia.org/wiki/Environment_variable#Default_Values_on_Microsoft_Windows

**Comment by eed3si9n** [comment]
`%HOMEPATH%` doesn't include the drive name. `%USERPROFILE%` seems to work.
